import { initializeApp } from "firebase/app";
import { getFirestore, setDoc, doc } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "AIzaSyDzOel-toXx7oT3DJ1GqgerW-X6dIdsyh0",
  authDomain: "desmoproductsonline.firebaseapp.com",
  projectId: "desmoproductsonline",
  storageBucket: "desmoproductsonline.firebasestorage.app",
  messagingSenderId: "684470912687",
  appId: "1:684470912687:web:9b31a83fb8217cd691f65a",
  measurementId: "G-6MM332FX5Y"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const DEFAULT_PRODUCTS = [
  {
    id: "LT240A15",
    name: "240V Loadtester",
    sku: "LT240A15",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 236,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "B400",
    name: "GS 0008 (WP) 400A Barrier",
    sku: "B400",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 45,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "B600",
    name: "GS 6029 (WP) 600A Barrier",
    sku: "B600",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 45,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "NT01",
    name: "HG 2101 Neutral Tag (50 per pack)",
    sku: "NT01",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 39,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "ID02",
    name: "HG2102 ID Tag (20/pack, double legged)",
    sku: "ID02",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 6.5,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "RAL2010",
    name: "RAL2010 Meter Seal - Signal Orange",
    sku: "RAL2010",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 62,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "RAL2005",
    name: "RAL2005 Meter Seal - Luminous Orange",
    sku: "RAL2005",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 62,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "RAL6004",
    name: "RAL6004 Meter Seal - Green",
    sku: "RAL6004",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 62,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "RAL5019",
    name: "RAL5019 Meter Seal - Blue",
    sku: "RAL5019",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 62,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "RAL1004",
    name: "RAL1004 Meter Seal - Yellow",
    sku: "RAL1004",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 62,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "RAL9003",
    name: "RAL9003 Meter Seal - White",
    sku: "RAL9003",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 62,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "RAL4005",
    name: "RAL4005 Meter Seal - Purple",
    sku: "RAL4005",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 62,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "RAL1001",
    name: "RAL1001 Meter Seal - Beige",
    sku: "RAL1001",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 62,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "RAL3000",
    name: "RAL3000 Meter Seal - Red",
    sku: "RAL3000",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 62,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "RAL3015",
    name: "RAL3015 Meter Seal - Pink",
    sku: "RAL3015",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 62,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "RAL6027",
    name: "RAL6027 Meter Seal - Light Blue",
    sku: "RAL6027",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 62,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "RAL7000",
    name: "RAL7000 Meter Seal - Grey",
    sku: "RAL7000",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 62,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "RAL8025",
    name: "RAL8025 Meter Seal - Brown",
    sku: "RAL8025",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 62,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "RAL9011",
    name: "RAL9011 Meter Seal - Black",
    sku: "RAL9011",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 62,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "ICT-717",
    name: "Circuit Test Control Box, Hand Piece & Wand",
    sku: "ICT-717",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 1620,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "RCD-PLD1",
    name: "RCD / Polarity Tester",
    sku: "RCD/PLD1",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 63.6,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "GL15",
    name: "15W Bayonet globes for RCD/PLD1",
    sku: "GL15",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 3.3,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "DFP2",
    name: "Fused Probe (set of red & black)",
    sku: "DFP2",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 48,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "DFP1",
    name: "Fused Probe Single",
    sku: "DFP1",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 24,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "FE2",
    name: "Double Ended Fuse Extractor",
    sku: "FE2",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 204.5,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "CP3",
    name: "Continuity, Phasing & Insulation Resistance Test Unit",
    sku: "CP3",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 77,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "ALN1",
    name: "Alligator Clip (Black)",
    sku: "ALN1",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 8,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "SALT1",
    name: "Satchels for Loadtester",
    sku: "SALT1",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 21,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
  {
    id: "LT7A",
    name: "Loadtester 7A HRC Fuses (per pack of 10)",
    sku: "LT7A",
    description: "",
    imageUrl: "",
    baseWholesalePrice: 12.5,
    isRestricted: false,
    quantityBreaks: [],
    category: "General",
    stock: 100,
    allowBackorders: true,
    weightKg: 1,
    lengthCm: 10,
    widthCm: 10,
    heightCm: 10
  },
];

async function seed() {
  for (const product of DEFAULT_PRODUCTS) {
    try {
      await setDoc(doc(db, "products", product.id), product);
      console.log(`Added product: ${product.name}`);
    } catch (error) {
      console.error(`Error adding product ${product.name}:`, error);
    }
  }
  console.log("All products seeded successfully.");
  process.exit(0);
}

seed();
