import fs from 'fs';

const filePath = '/Users/bjmack/Downloads/Apps/Desmo/src/context/PortalContext.tsx';
let content = fs.readFileSync(filePath, 'utf-8');

const replacementProducts = `  {
    id: "METERSEAL-SIGNAL-ORANGE",
    name: "KWh Meter Seals (Pack) - Signal Orange",
    sku: "METERSEAL-SIGNAL-ORANGE",
    description: "Purpose: Security and tamper-evident seals used by power distribution companies to lock kWh meter enclosures after installation or testing. They ensure secondary contractors or consumers cannot manipulate power meter configurations without breaking the visual seal code.",
    imageUrl: "placeholder",
    baseWholesalePrice: 45.00,
    isRestricted: true,
    autoApprove: false,
    category: "Safety Compliance",
    stock: 200,
    allowBackorders: true,
    weightKg: 1.5,
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10
  },
  {
    id: "METERSEAL-GREEN",
    name: "KWh Meter Seals (Pack) - Green",
    sku: "METERSEAL-GREEN",
    description: "Purpose: Security and tamper-evident seals used by power distribution companies to lock kWh meter enclosures after installation or testing. They ensure secondary contractors or consumers cannot manipulate power meter configurations without breaking the visual seal code.",
    imageUrl: "placeholder",
    baseWholesalePrice: 45.00,
    isRestricted: true,
    autoApprove: false,
    category: "Safety Compliance",
    stock: 200,
    allowBackorders: true,
    weightKg: 1.5,
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10
  },
  {
    id: "METERSEAL-YELLOW",
    name: "KWh Meter Seals (Pack) - Yellow",
    sku: "METERSEAL-YELLOW",
    description: "Purpose: Security and tamper-evident seals used by power distribution companies to lock kWh meter enclosures after installation or testing. They ensure secondary contractors or consumers cannot manipulate power meter configurations without breaking the visual seal code.",
    imageUrl: "placeholder",
    baseWholesalePrice: 45.00,
    isRestricted: true,
    autoApprove: false,
    category: "Safety Compliance",
    stock: 200,
    allowBackorders: true,
    weightKg: 1.5,
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10
  },
  {
    id: "METERSEAL-WHITE",
    name: "KWh Meter Seals (Pack) - White",
    sku: "METERSEAL-WHITE",
    description: "Purpose: Security and tamper-evident seals used by power distribution companies to lock kWh meter enclosures after installation or testing. They ensure secondary contractors or consumers cannot manipulate power meter configurations without breaking the visual seal code.",
    imageUrl: "placeholder",
    baseWholesalePrice: 45.00,
    isRestricted: true,
    autoApprove: false,
    category: "Safety Compliance",
    stock: 200,
    allowBackorders: true,
    weightKg: 1.5,
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10
  },
  {
    id: "METERSEAL-BEIGE",
    name: "KWh Meter Seals (Pack) - Beige",
    sku: "METERSEAL-BEIGE",
    description: "Purpose: Security and tamper-evident seals used by power distribution companies to lock kWh meter enclosures after installation or testing. They ensure secondary contractors or consumers cannot manipulate power meter configurations without breaking the visual seal code.",
    imageUrl: "placeholder",
    baseWholesalePrice: 45.00,
    isRestricted: true,
    autoApprove: false,
    category: "Safety Compliance",
    stock: 200,
    allowBackorders: true,
    weightKg: 1.5,
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10
  },
  {
    id: "METERSEAL-RED",
    name: "KWh Meter Seals (Pack) - Red",
    sku: "METERSEAL-RED",
    description: "Purpose: Security and tamper-evident seals used by power distribution companies to lock kWh meter enclosures after installation or testing. They ensure secondary contractors or consumers cannot manipulate power meter configurations without breaking the visual seal code.",
    imageUrl: "placeholder",
    baseWholesalePrice: 45.00,
    isRestricted: true,
    autoApprove: false,
    category: "Safety Compliance",
    stock: 200,
    allowBackorders: true,
    weightKg: 1.5,
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10
  },
  {
    id: "METERSEAL-PINK",
    name: "KWh Meter Seals (Pack) - Pink",
    sku: "METERSEAL-PINK",
    description: "Purpose: Security and tamper-evident seals used by power distribution companies to lock kWh meter enclosures after installation or testing. They ensure secondary contractors or consumers cannot manipulate power meter configurations without breaking the visual seal code.",
    imageUrl: "placeholder",
    baseWholesalePrice: 45.00,
    isRestricted: true,
    autoApprove: false,
    category: "Safety Compliance",
    stock: 200,
    allowBackorders: true,
    weightKg: 1.5,
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10
  },
  {
    id: "METERSEAL-PURPLE",
    name: "KWh Meter Seals (Pack) - Purple",
    sku: "METERSEAL-PURPLE",
    description: "Purpose: Security and tamper-evident seals used by power distribution companies to lock kWh meter enclosures after installation or testing. They ensure secondary contractors or consumers cannot manipulate power meter configurations without breaking the visual seal code.",
    imageUrl: "placeholder",
    baseWholesalePrice: 45.00,
    isRestricted: true,
    autoApprove: false,
    category: "Safety Compliance",
    stock: 200,
    allowBackorders: true,
    weightKg: 1.5,
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10
  },
  {
    id: "METERSEAL-LIGHT-BLUE",
    name: "KWh Meter Seals (Pack) - L/ Blue",
    sku: "METERSEAL-LIGHT-BLUE",
    description: "Purpose: Security and tamper-evident seals used by power distribution companies to lock kWh meter enclosures after installation or testing. They ensure secondary contractors or consumers cannot manipulate power meter configurations without breaking the visual seal code.",
    imageUrl: "placeholder",
    baseWholesalePrice: 45.00,
    isRestricted: true,
    autoApprove: false,
    category: "Safety Compliance",
    stock: 200,
    allowBackorders: true,
    weightKg: 1.5,
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10
  },
  {
    id: "METERSEAL-GREY",
    name: "KWh Meter Seals (Pack) - Grey",
    sku: "METERSEAL-GREY",
    description: "Purpose: Security and tamper-evident seals used by power distribution companies to lock kWh meter enclosures after installation or testing. They ensure secondary contractors or consumers cannot manipulate power meter configurations without breaking the visual seal code.",
    imageUrl: "placeholder",
    baseWholesalePrice: 45.00,
    isRestricted: true,
    autoApprove: false,
    category: "Safety Compliance",
    stock: 200,
    allowBackorders: true,
    weightKg: 1.5,
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10
  },
  {
    id: "METERSEAL-BROWN",
    name: "KWh Meter Seals (Pack) - Brown",
    sku: "METERSEAL-BROWN",
    description: "Purpose: Security and tamper-evident seals used by power distribution companies to lock kWh meter enclosures after installation or testing. They ensure secondary contractors or consumers cannot manipulate power meter configurations without breaking the visual seal code.",
    imageUrl: "placeholder",
    baseWholesalePrice: 45.00,
    isRestricted: true,
    autoApprove: false,
    category: "Safety Compliance",
    stock: 200,
    allowBackorders: true,
    weightKg: 1.5,
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10
  },
  {
    id: "METERSEAL-BLUE",
    name: "KWh Meter Seals (Pack) - Blue",
    sku: "METERSEAL-BLUE",
    description: "Purpose: Security and tamper-evident seals used by power distribution companies to lock kWh meter enclosures after installation or testing. They ensure secondary contractors or consumers cannot manipulate power meter configurations without breaking the visual seal code.",
    imageUrl: "placeholder",
    baseWholesalePrice: 45.00,
    isRestricted: true,
    autoApprove: false,
    category: "Safety Compliance",
    stock: 200,
    allowBackorders: true,
    weightKg: 1.5,
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10
  },
  {
    id: "METERSEAL-BLACK",
    name: "KWh Meter Seals (Pack) - Black",
    sku: "METERSEAL-BLACK",
    description: "Purpose: Security and tamper-evident seals used by power distribution companies to lock kWh meter enclosures after installation or testing. They ensure secondary contractors or consumers cannot manipulate power meter configurations without breaking the visual seal code.",
    imageUrl: "placeholder",
    baseWholesalePrice: 45.00,
    isRestricted: true,
    autoApprove: false,
    category: "Safety Compliance",
    stock: 200,
    allowBackorders: true,
    weightKg: 1.5,
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10
  },
  {
    id: "METERSEAL-FLUORO-ORANGE",
    name: "KWh Meter Seals (Pack) - Fluoro Orange",
    sku: "METERSEAL-FLUORO-ORANGE",
    description: "Purpose: Security and tamper-evident seals used by power distribution companies to lock kWh meter enclosures after installation or testing. They ensure secondary contractors or consumers cannot manipulate power meter configurations without breaking the visual seal code.",
    imageUrl: "placeholder",
    baseWholesalePrice: 45.00,
    isRestricted: true,
    autoApprove: false,
    category: "Safety Compliance",
    stock: 200,
    allowBackorders: true,
    weightKg: 1.5,
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10
  }`;

const oldProductRegex = /  \{\n    id: "METERSEAL",[\s\S]+?\]\n  \}/;
content = content.replace(oldProductRegex, replacementProducts);

const oldAllowed = 'allowedProducts: ["DP-OSC-200", "METERSEAL"]';
const newAllowed = 'allowedProducts: ["DP-OSC-200", "METERSEAL-SIGNAL-ORANGE", "METERSEAL-GREEN", "METERSEAL-YELLOW", "METERSEAL-WHITE", "METERSEAL-BEIGE", "METERSEAL-RED", "METERSEAL-PINK", "METERSEAL-PURPLE", "METERSEAL-LIGHT-BLUE", "METERSEAL-GREY", "METERSEAL-BROWN", "METERSEAL-BLUE", "METERSEAL-BLACK", "METERSEAL-FLUORO-ORANGE"]';
content = content.replace(oldAllowed, newAllowed);

fs.writeFileSync(filePath, content, 'utf-8');
console.log("Successfully replaced METERSEAL product logic");
